apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: secretary
  namespace: kube-system
  labels:
    application: secretary
    version: v0.3.1
spec:
  replicas: 1
  selector:
    matchLabels:
      application: secretary
  template:
    metadata:
      labels:
        application: secretary
        version: v0.3.1
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        iam.amazonaws.com/role: "{{ .LocalID }}-app-secretary"
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - name: secretary
        image: registry.opensource.zalan.do/teapot/secretary:v0.3.1
        args:
        - --all-namespaces
        - --service-account=default
        - --interval=10m
        - --aws-iid-secret
        resources:
          requests:
            cpu: 5m
            memory: 20Mi
